// Code generated by sqlc. DO NOT EDIT.
// versions:
// sqlc v1.31.1
// source: blogs.sql

package db

import (
	"context"
)

const countBlogs = `-- name: CountBlogs :one
SELECT COUNT(*) FROM blogs
`

func (q *Queries) CountBlogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlog = `-- name: CreateBlog :one
INSERT INTO blogs (headline, body, user_id) 
VALUES ($1, $2, $3) 
RETURNING blog_id, headline, body, created_at, updated_at, user_id
`

type CreateBlogParams struct {
	Headline string `json:"headline"`
	Body     string `json:"body"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, createBlog, arg.Headline, arg.Body, arg.UserID)
	var i Blog
	err := row.Scan(
		&i.BlogID,
		&i.Headline,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs WHERE blog_id = $1 AND user_id = $2
`

type DeleteBlogParams struct {
	BlogID int64 `json:"blog_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteBlog(ctx context.Context, arg DeleteBlogParams) error {
	_, err := q.db.Exec(ctx, deleteBlog, arg.BlogID, arg.UserID)
	return err
}

const deleteBlogByID = `-- name: DeleteBlogByID :exec
DELETE FROM blogs WHERE blog_id = $1
`

func (q *Queries) DeleteBlogByID(ctx context.Context, blogID int64) error {
	_, err := q.db.Exec(ctx, deleteBlogByID, blogID)
	return err
}

const deleteBlogsByUser = `-- name: DeleteBlogsByUser :exec
DELETE FROM blogs WHERE user_id = $1
`

func (q *Queries) DeleteBlogsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteBlogsByUser, userID)
	return err
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT blog_id, headline, body, created_at, updated_at, user_id FROM blogs WHERE blog_id = $1 LIMIT 1
`

func (q *Queries) GetBlogByID(ctx context.Context, blogID int64) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogByID, blogID)
	var i Blog
	err := row.Scan(
		&i.BlogID,
		&i.Headline,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT blog_id, headline, body, created_at, updated_at, user_id FROM blogs 
ORDER BY created_at DESC 
OFFSET $1 LIMIT $2
`

type ListBlogsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListBlogs(ctx context.Context, arg ListBlogsParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, listBlogs, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.BlogID,
			&i.Headline,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs SET
    headline = COALESCE($2, headline),
    body = COALESCE($3, body),
    updated_at = NOW()
WHERE blog_id = $1 AND user_id = $4
RETURNING blog_id, headline, body, created_at, updated_at, user_id
`

type UpdateBlogParams struct {
	BlogID   int64  `json:"blog_id"`
	Headline string `json:"headline"`
	Body     string `json:"body"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.db.QueryRow(ctx, updateBlog,
		arg.BlogID,
		arg.Headline,
		arg.Body,
		arg.UserID,
	)
	var i Blog
	err := row.Scan(
		&i.BlogID,
		&i.Headline,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
