// Code generated by sqlc. DO NOT EDIT.
// versions:
// sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const countCommentsByBlogID = `-- name: CountCommentsByBlogID :one
SELECT COUNT(*) FROM comments WHERE blog_id = $1
`

func (q *Queries) CountCommentsByBlogID(ctx context.Context, blogID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByBlogID, blogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (body, blog_id, user_id) 
VALUES ($1, $2, $3) 
RETURNING comment_id, body, created_at, updated_at, blog_id, user_id
`

type CreateCommentParams struct {
	Body   string `json:"body"`
	BlogID int64  `json:"blog_id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.Body, arg.BlogID, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlogID,
		&i.UserID,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE comment_id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.CommentID, arg.UserID)
	return err
}

const deleteCommentByID = `-- name: DeleteCommentByID :exec
DELETE FROM comments WHERE comment_id = $1
`

func (q *Queries) DeleteCommentByID(ctx context.Context, commentID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentByID, commentID)
	return err
}

const deleteCommentsByBlog = `-- name: DeleteCommentsByBlog :exec
DELETE FROM comments WHERE blog_id = $1
`

func (q *Queries) DeleteCommentsByBlog(ctx context.Context, blogID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentsByBlog, blogID)
	return err
}

const deleteCommentsByUser = `-- name: DeleteCommentsByUser :exec
DELETE FROM comments WHERE user_id = $1
`

func (q *Queries) DeleteCommentsByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCommentsByUser, userID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT comment_id, body, created_at, updated_at, blog_id, user_id FROM comments WHERE comment_id = $1 LIMIT 1
`

func (q *Queries) GetCommentByID(ctx context.Context, commentID int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, commentID)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlogID,
		&i.UserID,
	)
	return i, err
}

const listCommentsByBlogID = `-- name: ListCommentsByBlogID :many
SELECT comment_id, body, created_at, updated_at, blog_id, user_id FROM comments 
WHERE blog_id = $1 
ORDER BY created_at DESC 
OFFSET $2 LIMIT $3
`

type ListCommentsByBlogIDParams struct {
	BlogID int64 `json:"blog_id"`
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListCommentsByBlogID(ctx context.Context, arg ListCommentsByBlogIDParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByBlogID, arg.BlogID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlogID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET
    body = $2,
    updated_at = NOW()
WHERE comment_id = $1 AND user_id = $3
RETURNING comment_id, body, created_at, updated_at, blog_id, user_id
`

type UpdateCommentParams struct {
	CommentID int64  `json:"comment_id"`
	Body      string `json:"body"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.CommentID, arg.Body, arg.UserID)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BlogID,
		&i.UserID,
	)
	return i, err
}
