// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error) // Für Queries ohne Rückgabe
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)         // Für Queries mit mehreren Zeilen
	QueryRow(context.Context, string, ...interface{}) pgx.Row                // Für Queries mit genau einer Zeile
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
