// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Blog struct {
	BlogID    int64     `json:"blog_id"`
	Headline  string    `json:"headline"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    int64     `json:"user_id"`
}

type Comment struct {
	CommentID int64     `json:"comment_id"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	BlogID    int64     `json:"blog_id"`
	UserID    int64     `json:"user_id"`
}

type User struct {
	UserID     int64     `json:"user_id"`
	Username   string    `json:"username"`
	Firstname  string    `json:"firstname"`
	Lastname   string    `json:"lastname"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	Birthday   time.Time `json:"birthday"`
	Role       string    `json:"role"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	LastOnline time.Time `json:"last_online"`
}
