// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountBlogs(ctx context.Context) (int64, error)
	CountCommentsByBlogID(ctx context.Context, blogID int64) (int64, error)
	CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBlog(ctx context.Context, arg DeleteBlogParams) error
	DeleteBlogByID(ctx context.Context, blogID int64) error
	DeleteBlogsByUser(ctx context.Context, userID int64) error
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	DeleteCommentByID(ctx context.Context, commentID int64) error
	DeleteCommentsByBlog(ctx context.Context, blogID int64) error
	DeleteCommentsByUser(ctx context.Context, userID int64) error
	DeleteUser(ctx context.Context, userID int64) error
	GetBlogByID(ctx context.Context, blogID int64) (Blog, error)
	GetCommentByID(ctx context.Context, commentID int64) (Comment, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserPublic(ctx context.Context, userID int64) (GetUserPublicRow, error)
	ListBlogs(ctx context.Context, arg ListBlogsParams) ([]Blog, error)
	ListCommentsByBlogID(ctx context.Context, arg ListCommentsByBlogIDParams) ([]Comment, error)
	UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateLastOnline(ctx context.Context, userID int64) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
