// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, firstname, lastname, email, password, birthday, role, last_online
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING user_id, username, firstname, lastname, email, password, birthday, role, created_at, updated_at, last_online
`

type CreateUserParams struct {
	Username   string    `json:"username"`
	Firstname  string    `json:"firstname"`
	Lastname   string    `json:"lastname"`
	Email      string    `json:"email"`
	Password   string    `json:"password"`
	Birthday   time.Time `json:"birthday"`
	Role       string    `json:"role"`
	LastOnline time.Time `json:"last_online"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
		arg.Birthday,
		arg.Role,
		arg.LastOnline,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOnline,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, firstname, lastname, email, password, birthday, role, created_at, updated_at, last_online FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOnline,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, firstname, lastname, email, password, birthday, role, created_at, updated_at, last_online FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOnline,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, firstname, lastname, email, password, birthday, role, created_at, updated_at, last_online FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOnline,
	)
	return i, err
}

const getUserPublic = `-- name: GetUserPublic :one
SELECT user_id, username, firstname, lastname, role, last_online 
FROM users WHERE user_id = $1 LIMIT 1
`

type GetUserPublicRow struct {
	UserID     int64     `json:"user_id"`
	Username   string    `json:"username"`
	Firstname  string    `json:"firstname"`
	Lastname   string    `json:"lastname"`
	Role       string    `json:"role"`
	LastOnline time.Time `json:"last_online"`
}

func (q *Queries) GetUserPublic(ctx context.Context, userID int64) (GetUserPublicRow, error) {
	row := q.db.QueryRow(ctx, getUserPublic, userID)
	var i GetUserPublicRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Role,
		&i.LastOnline,
	)
	return i, err
}

const updateLastOnline = `-- name: UpdateLastOnline :exec
UPDATE users SET last_online = NOW() WHERE user_id = $1
`

func (q *Queries) UpdateLastOnline(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, updateLastOnline, userID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    firstname = COALESCE($2, firstname),
    lastname = COALESCE($3, lastname),
    email = COALESCE($4, email),
    birthday = COALESCE($5, birthday),
    updated_at = NOW()
WHERE user_id = $1
RETURNING user_id, username, firstname, lastname, email, password, birthday, role, created_at, updated_at, last_online
`

type UpdateUserParams struct {
	UserID    int64     `json:"user_id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Email     string    `json:"email"`
	Birthday  time.Time `json:"birthday"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Birthday,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Email,
		&i.Password,
		&i.Birthday,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastOnline,
	)
	return i, err
}
